-- 정보 테이블들에 등록일, 수정일 컬럼 추가
-- 기존 테이블에 컬럼을 추가하는 ALTER TABLE 문

-- 1. 교회 정보 테이블
ALTER TABLE tb_church_info 
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일' AFTER churchViewCount,
ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일' AFTER created_at;

-- 2. 회사 정보 테이블
ALTER TABLE tb_comp_info 
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일' AFTER resignations,
ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일' AFTER created_at;

-- 3. 외주 정보 테이블
ALTER TABLE tb_outsource_info 
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일' AFTER outsourceViewCount,
ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일' AFTER created_at;

-- 4. 식당 정보 테이블
ALTER TABLE tb_restaurant_info 
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일' AFTER restaurantViewCount,
ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일' AFTER created_at;

-- 5. 대학 정보 테이블
ALTER TABLE tb_universityinfo 
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일' AFTER univViewCount,
ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일' AFTER created_at;

